
"""
Constants for models.py
"""

CATEGORY_MAX_LENGTH = 200
GROUPS_MAX_LENGTH = 100
EXPENSES_MAX_LENGTH = 200
EXPENSES_MAX_DIGITS = 10
EXPENSES_DECIMAL_PLACES = 2
USER_EXPENSE_MAX_DIGITS = 10
USEREXPENSE_DECIMAL_PLACES = 2

